### ISSUE TITLE
WSGIRequest' object has no attribute 'placeholder'

### ISSUE THREAD

**Issue by anishukserg** [aldryn/aldryn-reversion#19]
I would like to add an article I go in the admin in the article and get an error WSGIRequest' object has no attribute 'placeholder'

Trace https://gist.github.com/c932b6dde83f6bb453b3.git

**Comment by mkoistinen** [comment]
@anishukserg, I'm unable to view that gist. Can you post another?

**Comment by anishukserg** [comment]
I'm sorry, it true link
https://gist.github.com/anishukserg/c932b6dde83f6bb453b3

**Comment by jonasmcarson** [comment]
Running into the same issue.  Appreciate any ideas.
https://gist.github.com/jonasmcarson/88225a7780853c5c6ffd

**Comment by cyberstar** [comment]
Hi guys, can you please provide ``Django``  and ``django-reversion`` versions ?
If you are using ``Django>=1.8`` and/or ``django-reversion >=1.9.0`` then I think this  pr #25 should fix the issue (it is related to changes in ``django-reversion >=1.9.0``).

**Comment by anishukserg** [comment]
I'm using Dgango-1.7.10 and reversion-1.9.3

**Comment by cyberstar** [comment]
@anishukserg can you please check if issue is still present if you use pr #25 branch instead of master?

**Comment by anishukserg** [comment]
@cyberstar  thank you, It work. Now, I'm testing.

**Comment by cyberstar** [comment]
Should be fixed with #25, closing this issue, in case of any other issues that are still present after that PR, please create a new issue.
